### ISSUE TITLE
Ability to convert data given on stdin

### ISSUE THREAD

**Issue by zdenek-crha** [sitkevij/hex#15]
**Is your feature request related to a problem? Please describe.**

The `hexdump` command and many Unix/Linux utilities allow operating on `stdin` either naturally `cat FILE | util` or by supplying special file name "-" like `cat FILE | util -`. 

**Describe the solution you'd like**

If file name does not exist and it has name "-", read and process input from `stdin`

**Describe alternatives you've considered**

If file name is not supplied, check if there is an input on `stdin` and process it instead.

**Additional context**

Since `hx` is basically filter, those two invocations are the first ones I have tried and none has worked for me. It is not a deal breaker, but it might be considered as lack of polish that will hinder adoption of `hx` tool.

Especially since in the second case I get panic instead of nicely formatted error message:

```
$ cat FILE | hx -
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/haku/.cargo/registry/src/github.com-1ecc6299db9ec823/hx-0.2.1/src/lib.rs:223:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by sitkevij** [comment]
stdin feature released as v0.3.0.
