### ISSUE TITLE
--len argument causes hx to hang

### ISSUE THREAD

**Issue by HagaiHargil** [sitkevij/hex#24]
**Describe the bug**
Calling `hx` with the `-l` or `--len` argument causes it to hang indefinitely.

**To Reproduce**
`hx -l myfile.txt`

**Desktop (please complete the following information):**
 - OS: Arch linux

**Additional context**
Thanks for this great tool :)

**Comment by poliorcetics** [comment]
Some more informations:

```shell
# Hangs
❯ /target/debug/hx --len 3 target/debug/hx
^C

# Does not hang
❯ /target/debug/hx --len 3 < target/debug/hx
0x000000: 0xcf 0xfa 0xed                                    ...
   bytes: 3

# Does not hand
❯ /target/debug/hx target/debug/hx --len 3  
0x000000: 0xcf 0xfa 0xed                                    ...
   bytes: 3
```

The order of the arguments seem to matter, I think this something that's coming from the `libs.rs/is_stdin` function, I'll try to find either a fix or more informations.
