### ISSUE TITLE
Create a cargo binary package

### ISSUE THREAD

**Issue by iemejia** [sitkevij/hex#5]
It would be nice to be able to compile/install this by making `cargo install hex` or something similar.

**Comment by sitkevij** [comment]
@iemejia given hex is an application and not a library package, there are no plans as of yet to add to cargo.io. However as of 0.1.3, install binary from source instructions via cargo has been added to the README and Makefile at https://github.com/sitkevij/hex#install

**Comment by iemejia** [comment]
Ah ok, it is a pity, most other modernish cli tools in rust are easily installable via cargo too, e.g. bat, ripgrep, exa, fd-find, etc.

**Comment by sitkevij** [comment]
@iemejia I agree having a crates.io hosted crate would be a helpful addition, happy to investigate as time allows.

**Comment by iemejia** [comment]
Awesome! It will be nice to see it happening!
