### ISSUE TITLE
Hide prefixes such as `0x`

### ISSUE THREAD

**Issue by maekawatoshiki** [sitkevij/hex#64]
**Is your feature request related to a problem? Please describe.**
Currently, there's no options to disable prefixes like `0x` as far as I know.
The `hexdump` command doesn't show `0x` so I can show more digits in a line.

**Describe the solution you'd like**
It would be better to add an option to disable prefixes.

**Describe alternatives you've considered**
The option `-f, --format` could have values to disable prefixes.

**Additional context**

**Comment by sitkevij** [comment]
Hi @maekawatoshiki, optional disabling of `0x` prefixing would be a welcome addition. 

- Marked as help wanted.
- Feel free to submit a PR with proposed changes.
